include:
  - ./proxy.yaml
services:
  web:
    image: web_app
    depends_on: ["db"]
    build: 
      dockerfile: Dockerfile.python
    environment:
      - DB_HOST=db
      - DB_USER=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_PASSWORD}
      - DB_NAME=${MYSQL_DATABASE}
    networks:
      backend:
        ipv4_address: 172.20.0.5
  db:
    image: mysql:8  
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-p@ssw0rd}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-app}
      - MYSQL_USER=${MYSQL_USER:-P@$$W0rd}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-p@ssw0rd}
      - MYSQL_ROOT_HOST="%"
    networks:
      backend:
        ipv4_address: 172.20.0.10
      
networks:
  backend:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24
  